package com.hal.jws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://jws.hal.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloWorld {

	/**
	 * 
	 * @param params
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://jws.hal.com/", className = "com.hal.jws.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jws.hal.com/", className = "com.hal.jws.SayHelloResponse")
	public String sayHello(@WebParam(name = "params", targetNamespace = "") String params);

	/**
	 * 
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayToUser", targetNamespace = "http://client.jws.hal.com/", className = "com.hal.jws.client.SayToUser")
	@ResponseWrapper(localName = "sayToUserResponse", targetNamespace = "http://client.jws.hal.com/", className = "com.hal.jws.client.SayToUserResponse")
	public String sayToUser(@WebParam(name = "user", targetNamespace = "") User user);

}
